# Generated by Django 3.2.6 on 2021-08-25 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('VEHICLE', 'VEHICLE'), ('PROPERTY', 'PROPERTY'), ('MOBILE_PHONES_AND_TABLETS', 'MOBILE_PHONES_AND_TABLETS'), ('ELECTRONICS', 'ELECTRONICS'), ('HOME_AND_FURNITURE_APPLIANCES', 'HOME_AND_FURNITURE_APPLIANCES'), ('HEALTH_AND_BEAUTY', 'HEALTH_AND_BEAUTY'), ('FASHION', 'FASHION'), ('SPORTS_ARTS_AND_OUTDOOR', 'SPORTS_ARTS_AND_OUTDOOR'), ('SEEKING_WORK', 'SEEKING_WORK'), ('SERVICES', 'SERVICES'), ('JOBS', 'JOBS'), ('BABIES_AND_KIDS', 'BABIES_AND_KIDS'), ('ANIMALS_AND_PETS', 'ANIMALS_AND_PETS'), ('AGRICULTURE_AND_FOOD', 'AGRICULTURE_AND_FOOD'), ('COMMERCIAL_EQUIPMENT_AND_TOOLS', 'COMMERCIAL_EQUIPMENT_AND_TOOLS'), ('REPAIR_AND_CONSTRUCTION', 'REPAIR_AND_CONSTRUCTION')], max_length=30)),
                ('county', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default=product.models.Status['OPEN'], max_length=10)),
                ('views', models.IntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='prodimage')),
                ('index', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'productImage',
                'verbose_name_plural': 'productImages',
            },
        ),
    ]
