# Generated by Django 3.2.6 on 2021-09-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='boost_type',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Platinum', 'Platinum')], default='none', max_length=30, null=True, verbose_name='Boosted type'),
        ),
        migrations.AddField(
            model_name='product',
            name='boosted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
