# Generated by Django 3.2.6 on 2021-09-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210915_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='boost_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='boosted',
        ),
        migrations.CreateModel(
            name='BoostedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
