# Generated by Django 3.2.6 on 2021-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210926_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosteditem',
            name='type',
            field=models.CharField(choices=[('None', 'None'), ('Regular', 'Regular'), ('Premium', 'Premium'), ('Platinum', 'Platinum')], default='None', max_length=60),
        ),
    ]
