# Generated by Django 3.2.6 on 2021-08-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210826_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEHICLE', 'VEHICLE'), ('PROPERTY', 'PROPERTY'), ('MOBILE_PHONES_AND_TABLETS', 'MOBILE PHONES AND TABLETS'), ('ELECTRONICS', 'ELECTRONICS'), ('HOME_AND_FURNITURE_APPLIANCES', 'HOME_AND_FURNITURE_APPLIANCES'), ('HEALTH_AND_BEAUTY', 'HEALTH_AND_BEAUTY'), ('FASHION', 'FASHION'), ('SPORTS_ARTS_AND_OUTDOOR', 'SPORTS_ARTS_AND_OUTDOOR'), ('SEEKING_WORK', 'SEEKING_WORK'), ('SERVICES', 'SERVICES'), ('JOBS', 'JOBS'), ('BABIES_AND_KIDS', 'BABIES_AND_KIDS'), ('ANIMALS_AND_PETS', 'ANIMALS_AND_PETS'), ('AGRICULTURE_AND_FOOD', 'AGRICULTURE_AND_FOOD'), ('COMMERCIAL_EQUIPMENT_AND_TOOLS', 'COMMERCIAL_EQUIPMENT_AND_TOOLS'), ('REPAIR_AND_CONSTRUCTION', 'REPAIR_AND_CONSTRUCTION')], max_length=30),
        ),
    ]
