# Generated by Django 3.2.6 on 2021-09-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.CharField(default=30, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='boosteditem',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='boosteditem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='boosteditem',
            name='price',
        ),
        migrations.AlterField(
            model_name='boosteditem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.boostedtype', verbose_name='type'),
        ),
    ]
