# Generated by Django 3.2.6 on 2021-10-10 10:17

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_auto_20210926_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory', verbose_name='Sub category')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Job Group',
                'verbose_name_plural': 'Job Groups',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand', verbose_name='Sub category')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Model',
            },
        ),
        migrations.CreateModel(
            name='Jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('CV', models.FileField(upload_to='cvs/', verbose_name='Curriculum vitae')),
                ('jobgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.jobgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job application',
                'verbose_name_plural': 'Job applications',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='Model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.model'),
        ),
    ]
